FROM python:3.8-slim-buster

RUN apt-get update && apt-get upgrade -y

RUN apt-get install -y git

COPY requirements.txt /requirements.txt

RUN pip3 install --no-cache-dir -r /requirements.txt

WORKDIR /LazyPrincess

COPY start.sh /start.sh

RUN chmod +x /start.sh

CMD ["/bin/bash", "/start.sh"]

docker build -t Filmykeedha .

docker run -d Filmykeedha
