# Start from a base image with Python 3.7 installed

FROM python:3.7

# Set the working directory in the container

WORKDIR /app

# Copy the requirements file to the working directory

COPY requirements.txt .

# Install the required Python packages

RUN pip install -r requirements.txt

# Copy the entire project directory to the working directory

COPY . .

# Specify the command to run when the container starts

CMD ["python", "app.py"]
